"use client"

/**
 * AI Monthly Financial Digest
 *
 * Displays a Gemini-generated narrative summary of the user's current month.
 * Results are cached in Firestore (one generation per month).
 * Gracefully degrades when the AI service is not configured.
 */

import { memo, useEffect, useState } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Skeleton } from "@/components/ui/skeleton"
import { Sparkles, RefreshCw, Info } from "lucide-react"
import { useInsightsContext } from "@/contexts/dashboard/InsightsContext"

function getCurrentMonthLabel(): string {
  const now = new Date()
  return now.toLocaleString("en-US", { month: "long", year: "numeric" })
}

export const AIDigest = memo(function AIDigest() {
  const { digestText, digestLoading, digestNotConfigured, refreshDigest } =
    useInsightsContext()

  const [autoTriggered, setAutoTriggered] = useState(false)

  // Auto-load on first mount
  useEffect(() => {
    if (!autoTriggered && !digestText && !digestLoading && !digestNotConfigured) {
      setAutoTriggered(true)
      refreshDigest()
    }
  }, [autoTriggered, digestText, digestLoading, digestNotConfigured, refreshDigest])

  return (
    <Card className="drop-shadow-xl shadow-black/10">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <CardTitle className="text-base font-semibold flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-purple-500" />
            AI Monthly Summary — {getCurrentMonthLabel()}
          </CardTitle>
          {!digestNotConfigured && (
            <Button
              variant="ghost"
              size="sm"
              className="h-7 px-2 text-xs text-muted-foreground hover:text-foreground"
              onClick={() => refreshDigest(true)}
              disabled={digestLoading}
              aria-label="Regenerate AI summary"
            >
              <RefreshCw className={`h-3 w-3 mr-1 ${digestLoading ? "animate-spin" : ""}`} />
              Refresh
            </Button>
          )}
        </div>
      </CardHeader>

      <CardContent>
        {/* Loading skeleton */}
        {digestLoading && (
          <div className="space-y-2">
            <Skeleton className="h-4 w-full" />
            <Skeleton className="h-4 w-5/6" />
            <Skeleton className="h-4 w-4/6" />
          </div>
        )}

        {/* Not configured */}
        {!digestLoading && digestNotConfigured && (
          <div className="flex items-start gap-3 text-sm text-muted-foreground py-2">
            <Info className="h-4 w-4 flex-shrink-0 mt-0.5" />
            <div>
              <p className="font-medium text-foreground mb-1">AI insights not configured</p>
              <p>
                To enable AI-powered summaries, add a free{" "}
                <span className="font-medium">Gemini API key</span> to your ML service.
                Get one free at{" "}
                <code className="text-xs bg-muted px-1 rounded">aistudio.google.com</code>.
              </p>
            </div>
          </div>
        )}

        {/* Digest text */}
        {!digestLoading && !digestNotConfigured && digestText && (
          <div className="space-y-3">
            <p className="text-sm leading-relaxed text-foreground">{digestText}</p>
            <p className="text-xs text-muted-foreground flex items-center gap-1">
              <Sparkles className="h-3 w-3" />
              Generated by Gemini AI · Based on your transaction history
            </p>
          </div>
        )}

        {/* Empty state (no data yet) */}
        {!digestLoading && !digestNotConfigured && !digestText && (
          <div className="text-sm text-muted-foreground py-2 text-center">
            No summary available yet. Add some transactions first.
          </div>
        )}
      </CardContent>
    </Card>
  )
})
